<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cocktail_jv"
 *
 * Auto generated by Extension Builder 2020-01-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Cocktail JV',
    'description' => 'Ceci est une description.',
    'category' => 'plugin',
    'author' => 'Julien Vitte',
    'author_email' => 'vitte.julien@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
